version: '3.7'

networks:
  tasknetwork:

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - tasknetwork
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - tasknetwork
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  java:
    build: .
    networks:
      - tasknetwork
    depends_on:
      - elasticsearch
    ports:
      - 8080:8080

volumes:
  elasticsearch-data:
    driver: local